src/Entity/Coach.php
<?php

namespace App\Entity;

use App\Repository\CoachRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
 
/**
 * @ORM\Entity(repositoryClass=CoachRepository::class)
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=false)
 */
class Coach
{
    use TimestampableEntity;
    use SoftDeleteableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $achievements;

    /**
     * @ORM\Column(type="string", unique=true)
     * @Gedmo\Slug(fields={"first_name","last_name"}, updatable=true)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="coach")
     */
    private $products;

    /**
     * @ORM\ManyToMany(targetEntity=Game::class, inversedBy="coaches")
     */
    private $games;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $ordered;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="coach")
     */
    private $reviews;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="coaches", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $user;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->games = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAchievements(): ?string
    {
        return $this->achievements;
    }

    public function setAchievements(string $achievements): self
    {
        $this->achievements = $achievements;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCoach($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCoach() === $this) {
                $product->setCoach(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->addCoach($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            $game->removeCoach($this);
        }

        return $this;
    }

    public function getOrdered(): ?int
    {
        return $this->ordered;
    }

    public function setOrdered(int $ordered): self
    {
        $this->ordered = $ordered;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setCoach($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getCoach() === $this) {
                $review->setCoach(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/CoachController.php
<?php

namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CoachController extends AbstractController
{

    /**
     * @Route("coach/{slug}", name="app_team_show")
     */

    public function show($slug)
    {
        $teams = [
            'Vox Eminor',
            'Renegades',
            'FaZe',
        ];


        return $this->render('coaches/show.html.twig',[
            'coach'=>$slug,
            'teams'=>$teams,
        ]);
    }
}

templates/coaches/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %} Update {% endblock %}
{% block body %}
{{ form(form) }}
{% endblock %}

templates/coaches/homepage.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    {# <div class="row row-cols-1 row-cols-md-3"> #}
    <div class="coach-section">
    <div class="container">
        <div class="row" style="margin-left:32px">
        <form method="get" action="{{ path('show_coaches') }}">
        <div class="input-group" >
            <input type="search" name="term" value="{{ term }}" placeholder="Search" style="font-size:15px;"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Go</button>
            </div>
        </div>
        </form>
        </div>
        <div class="row justify-content-md-center">
        {% for coach in pagination %}
            <div class="col-lg-4">
                <div class="card">
                <img src="{{ asset ('images/cardbg.jpg') }}" alt="card backgroud" class="card-img ">
                <img src="{{ asset ('images/img_avatar3.png') }}" alt="profile image" class="profile-img mx-auto d-block">
                <h1 style="text-align:center;">{{ coach.firstName }} {{ coach.lastName }}</h1>
                <p class="job-title" style="text-align:center;">Coach</p>
                <p class="about" style="text-align:center;">{{ coach.achievements }}</p>
                {% if coach.reviews|length %}
                    <h5>{{ (coach.reviews|map(r => r.stars)|reduce((carry, v) => carry + v) / coach.reviews|length) | round(1, 'floor')}}</h5>
                {% else %}
                <p style="text-align:center;font-size:12px;">No reviews</p>
                {% endif %}
                <a href="{{ path ('show_coach', {slug: coach.slug}) }}" class="btn btn-primary">Profile</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

templates/coaches/mainindex.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if is_granted ("IS_AUTHENTICATED_REMEMBERED") %}

<div class="intro-section" id="home-section">
      
  <div class="slide-1" style="background-image: url('images/hero_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12">
            <div class="row align-items-center">
              <div class="col-lg-6 mb-4">
                <h1>Learn From The Expert</h1>
                <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsa nulla sed quis rerum amet natus quas necessitatibus.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
    {% else %}
<div class="intro-section" id="home-section">
  <div class="slide-1" style="background-image: url('images/hero_1.jpg');" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12">
          <div class="row align-items-center">
            <div class="col-lg-6 mb-4">
              <h1>Learn From The Expert</h1>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime ipsa nulla sed quis rerum amet natus quas necessitatibus.</p>
            </div>
            
            <div class="col-lg-5 ml-auto">
            <div class="form-box">
            <div class="form-group ">
              {{ form_start(registrationForm) }}
            </div>
                <h3 class="h4 text-black mb-4">Sign Up</h3>
              <div class="form-group">
              {{ form_widget(registrationForm.username,{'attr': {'class': 'form-control','placeholder':'Username'}}) }}</p>
              </div>
                <div class="form-group">
                <p>{{ form_widget(registrationForm.plainPassword.first,{'attr': {'class': 'form-control', 'placeholder':'Password'}}) }}</p>
                </div>
                <div class="form-group">
                <p>{{ form_widget(registrationForm.plainPassword.second,{'attr': {'class': 'form-control', 'placeholder':'Retype Password'}}) }}</p>
                </div>
              <div class="form-group">
              {{ form_widget(registrationForm.email, {'attr': {'class': 'form-control', 'placeholder':'Email adress'}}) }}
              </div>
              <div class="form-group">
              {{ form_label(registrationForm.agreeTerms) }}
              {{ form_widget(registrationForm.agreeTerms) }}
              </div>
              <div>
                  <button class="btn btn-lg btn-primary" type="submit">Sign Up</button>
                </div>
              {{ form_end(registrationForm) }}
              </div>
              </div>
            </div>
          </div>            
        </div>
      </div>
    </div>
  </div>
    {% endif %}
    <br>
    <br>
    <br>
    <hr class="container">

<div class="service-section" style="margin-top:1.3rem;">
    <div class="container">
            <div class="row mbr-justify-content-center">
                <div class="col-lg-6 mbr-col-md-10">
                    <div class="wrap">
                        <div class="ico-wrap">
                            <span class="mbr-iconfont fa-calendar fa"></span>
                        </div>
                        <div class="text-wrap vcenter">
                            <h2 class="mbr-fonts-style mbr-bold mbr-section-title3 display-5">Create
                                <span>A Plan</span>
                            </h2>
                            <p class="mbr-fonts-style text1 mbr-text display-6">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mbr-col-md-10">
                    <div class="wrap">
                        <div class="ico-wrap">
                            <span class="mbr-iconfont fa-globe fa"></span>
                        </div>
                        <div class="text-wrap vcenter">
                            <h2 class="mbr-fonts-style mbr-bold mbr-section-title3 display-5">Launch
                                <span>A Unique Project</span>
                            </h2>
                            <p class="mbr-fonts-style text1 mbr-text display-6">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mbr-col-md-10">
                    <div class="wrap">
                        <div class="ico-wrap">
                            <span class="mbr-iconfont fa-trophy fa"></span>
                        </div>
                        <div class="text-wrap vcenter">
                            <h2 class="mbr-fonts-style mbr-bold mbr-section-title3 display-5">Achieve <span>Your Goals</span></h2>
                            <p class="mbr-fonts-style text1 mbr-text display-6">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mbr-col-md-10">
                    <div class="wrap">
                        <div class="ico-wrap">
                            <span class="mbr-iconfont fa-volume-up fa"></span>
                        </div>
                        <div class="text-wrap vcenter">
                            <h2 class="mbr-fonts-style mbr-bold mbr-section-title3 display-5">Become <span>Successful</span></h2>
                            <p class="mbr-fonts-style text1 mbr-text display-6">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum</p>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

<hr class="container">

<div class="coach-section">
    <div class="container">
        <h1 class="heading">Meet Our Coaches</h1>
        <div class="row justify-content-md-center">
        {% for coach in topcoaches %}
            <div class="col-lg-4">
            <div class="card">
                    <img src="{{ asset ('images/cardbg.jpg') }}" alt="card backgroud" class="card-img ">
                    <img src="{{ asset ('images/img_avatar3.png') }}" alt="profile image" class="profile-img mx-auto d-block">
                    <h1 style="text-align:center;">{{ coach.firstName }} {{ coach.lastName }}</h1>
                    <p class="job-title" style="text-align:center;">Coach</p>
                    <p class="about" style="text-align:center;">{{ coach.achievements }}</p>
                    <a href="{{ path ('show_coach', {slug: coach.slug}) }}" class="btn btn-primary">Profile</a>
                    <ul class="social-media">
                        <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fab fa-google-plus-square"></i></a></li>
                    </ul>
            </div>
            </div>
        {% endfor %}
        <a href="{{ path ('show_coaches') }}" class="" style="text-decoration:none;color:#313131;font-size:1rem;">See more <i class="fas fa-chevron-circle-right"></i></a>
        </div>
        </div>
    </div>
</div>
	
</div>
</div>
</div>
</section>
{% endblock %}

templates/coaches/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col-lg-4">
    <p>Coaches</p>
    {% for coach in coaches %}
        <a class="q-title" href="{{ path('show_coach', { slug: coach.slug }) }}">{{ coach.firstName }} {{ coach.lastName }}</a>
        <br>
    {% else %}
        We couldn't find a coach!
    {% endfor %}
    </div>
    <div class="col-lg-4">
    <p>Genres</p>
    {% for genre in genres %}
        <a class="q-title" href="{{ path('genre_show', { slug: genre.slug }) }}">{{ genre.name }}</a>
        <br>
    {% else %}
        We couldn't find a genre!
    {% endfor %}
    </div>
    <div class="col-lg-4">
    <p>Games</p>      
    {% for game in games %}
        <a class="q-title" href="{{ path('show_game', { slug: game.slug }) }}">{{ game.name }}</a>
        <br>
    {% else %}
        We couldn't find a game!
    {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/coaches/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} Coach: {{ coach.firstName }} {{ coach.lastName }} {% endblock %}

{% block body %}
<div class="coach-section">
<div class="container d-flex justify-content-center">
    <div class="row">
        <div class="col-12">
                <div class="card" style="width:100%">
                    <img src="{{ asset ('images/cardbg.jpg') }}" alt="card backgroud" class="card-img ">
                    <img src="{{ asset ('images/img_avatar3.png') }}" alt="profile image" class="profile-img mx-auto d-block">
                    <h1 style="text-align:center;">{{ coach.firstName }} {{ coach.lastName }} {% if (reviewavg.avg | round(1, 'floor')) == 0 %}
                            {% else %}
                            - {{ reviewavg.avg | round(1, 'floor') }}
                            {% endif %}</h1>
                    <p class="job-title" style="text-align:center;">Coach</p>
                    <p class="about" style="text-align:center;">{{ coach.achievements }}</p>
                    {% if reviewitems is empty %}
                        No reviews
                    {% else %}
                        Review: {{ (reviewitems|map(r => r.stars)|reduce((carry, v) => carry + v) / reviewitems|length) | round(1, 'floor')}}
                    {% endif %}
                    <ul class="social-media">
                        <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter-square"></i></a></li>
                        <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fab fa-google-plus-square"></i></a></li>
                    </ul>
                </div>                               
        </div>
    </div>
</div>
</div>
    <div class="container">
    <ul class="list-unstyled">
        <div class="row justify-content-center">
        {% for product in products %}
        <div class="card" style="background:white;color:black;">
                <div class="d-flex justify-content-center">
                    <div class="mx-3 py-2">
                       <p style="text-align:center;">{{ product.type }}</p>Description - {{ product.description }} : {{ product.price }}$
                       <p>{{ product.game.name }}
                    </div>
                    {% if is_granted("ROLE_COACH") and coach.user.id == app.user.id %}
                    <div class="flex-fill pt-2" style="min-width: 90px;">
                    <form action="{{ path('product_delete', { id: product.id }) }}" method="POST" >
                        <input type="hidden" name="_method" value="DELETE"/>
                        <button type="submit" class="btn btn-outline-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                    </form>
                            <a class="btn btn-outline-primary btn-sm" href="{{ path ('product_update', { id: product.id }) }}">
                            <i class="fas fa-pen"></i>
                            </a>
                    </div>
                    {% endif %}
                </div>
        </div>
        {% endfor %}
        </div>
    </ul>
    </div>
    <div class="container">
    {% if is_granted('ROLE_COACH') and coach.user.id == app.user.id %}
    <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Create product
        </a>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            {{ form(form) }}
        </div>
    </div>
    <a href="{{ path('ch_update', {id: coach.id})}}" class="btn btn-secondary mb-3"> Coach update </a>
    <form action="{{ path('remove_id', { id: coach.id }) }}" method="POST" >
        <input type="hidden" name="_method" value="DELETE"/>
        <button type="submit" class="btn btn-danger">Remove coach</button>
    </form>
    {% endif %}

    {% if is_granted("ROLE_COACH") %}
    {% else %}
    <div class="mt-5 d-flex justify-content-center">
        <div class="card card-body">
            {{ form_start(reviewform) }}
            <div class="rater">
            {{ form_label(reviewform.stars) }}
            <i class="far fa-star checked" id="one"></i>
            <i class="far fa-star unchecked" id="two"></i>
            <i class="far fa-star unchecked" id="three"></i>
            <i class="far fa-star unchecked" id="four"></i>
            <i class="far fa-star unchecked" id="five"></i>
            </div>           
            {{ form_row(reviewform.description, {'attr': {'class': 'form-control'}}) }}
            <div class="row">
                <div class="col">
                <br>
            {{ form_widget(reviewform.save, {'attr': {'class': 'btn btn-primary'}}) }}
                </div>
            </div class="row">
            {{ form_end(reviewform) }}
        </div>
    </div>
    {% endif %}
    </div>
    <div class="m-5">
        {% for reviewitem in reviewitems %}
            <div class="card card-body"
                <li>
                <h5> Stars: {{ reviewitem.stars }} </h5>
                    <p> Description: {{ reviewitem.description }} </p>
                </li>
            </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

templates/coaches/signup.html.twig
{% extends 'base.html.twig' %}
{% block title %} Sign up {% endblock %}
{% block body %}
{{ form_start(form) }}
    <div class="row">
        <div class="col">
            {{ form_row(form.firstName, {'attr': {'class': 'form-control'}}) }}
        </div class="col">
        <div class="col">
            {{ form_row(form.lastName, {'attr': {'class': 'form-control'}}) }}
        </div class="col">
        </div class="row">
        <div class="row">
        <div class="col">
            {{ form_label(form.games) }}
            {{ form_widget(form.games) }}
            <a class="btn btn-dark" href="{{ path('game_create') }}">Add a new game</a>
        </div class="col">
        <div class="col">
            {{ form_row(form.achievements, {'attr': {'class': 'form-control'}}) }}
            <div class="float-right">{{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}</div>
        </div class="col">
        </div class="row">
{{ form_end(form) }}
{% endblock %}